#!/bin/sh

unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS

[[ -x /etc/vnc/xstartup ]] && exec /etc/vnc/xstartup
[[ -r $HOME/.Xresources ]] && xrdb $HOME/.Xresources

xsetroot -solid grey
fluxbox &
sleep 5
xterm -maximized -e "tail -f ${HOME}/allout.txt" -ls -title "$VNCDESKTOP Desktop" &

