#!/bin/sh

unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS

[[ -x /etc/vnc/xstartup ]] && exec /etc/vnc/xstartup
[[ -r $SELENIUM_HOME/.Xresources ]] && xrdb $SELENIUM_HOME/.Xresources

xsetroot -solid grey
fluxbox &
sleep 5
xterm -maximized -e "java -jar $SELENIUM_PATH -port 4445 2>&1 | tee -a $SELENIUM_HOME/allout.txt" &
